name: openff-interchange-docs
channels:
  - conda-forge
dependencies:
  # Base depends
  - python
  - pip
  - pydantic
  - pint
  - openmm
  - openff-toolkit
  - openff-units
  - openff-utilities
  - jax
  - ele
  # readthedocs dependencies
  - myst-parser
  - numpydoc
  - sphinx_rtd_theme
