name: lint

on:
  push:
    paths:
      - 'openff/**.py'
      - 'setup.cfg'

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.7'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install linters
        run: |
          pip install black isort flake8 flake8-bugbear

      - name: Run black
        run: |
          black openff --check

      - name: Run black
        run: |
          isort --check-only openff

      - name: Run flake8
        run: |
          flake8 openff
