name: lint

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install linters
        run: |
          pip install black isort flake8 flake8-bugbear flake8-absolute-import flake8-pytest-style

      - name: Run black
        run: |
          black openff --check

      - name: Run isort
        run: |
          isort --check-only openff

      - name: Run flake8
        run: |
          flake8 openff
