name: lint

on:
  push:
    branches:
      - "master"
      - "maintenance/.+"
  pull_request:
    branches:
      - "master"
      - "maintenance/.+"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.7'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install linters
        run: |
          pip install black isort flake8 flake8-bugbear flake8-absolute-import

      - name: Run black
        run: |
          black openff --check

      - name: Run black
        run: |
          isort --check-only openff

      - name: Run flake8
        run: |
          flake8 openff
